-- Наполнение канона master_page_types (Фаза 1, seed). СГЕНЕРИРОВАНО scripts/gen-seed.
-- Идемпотентно: ON CONFLICT (code) DO UPDATE. Повторный запуск не плодит дубли.
-- НЕ трогает: placeholders, rules, движок, дизайны. Только канон + backfill type_id.
-- Откат наполнения:  delete from master_page_types;  (предварительно обнулив ссылки:
--   update spread_templates set master_page_type_id = null where master_page_type_id is not null;)

insert into master_page_types
  (code, display_name, family_id, page_role, slot_capacity, canonical_slots, page_type, is_active, notes)
values
  ('common-collage-3', 'Коллаж из 3 фото', 'common-section', 'common', '{"photos_collage":3}'::jsonb, '[{"label":"collagephoto_1","type":"photo","required":false},{"label":"collagephoto_2","type":"photo","required":false},{"label":"collagephoto_3","type":"photo","required":false}]'::jsonb, null, true, null),
  ('common-collage-4', 'Коллаж из 4 фото', 'common-section', 'common', '{"photos_collage":4}'::jsonb, '[{"label":"collagephoto_1","type":"photo","required":false},{"label":"collagephoto_2","type":"photo","required":false},{"label":"collagephoto_3","type":"photo","required":false},{"label":"collagephoto_4","type":"photo","required":false}]'::jsonb, null, true, null),
  ('common-collage-5', 'Коллаж из 5 фото', 'common-section', 'common', '{"photos_collage":5}'::jsonb, '[{"label":"collagephoto_1","type":"photo","required":false},{"label":"collagephoto_2","type":"photo","required":false},{"label":"collagephoto_3","type":"photo","required":false},{"label":"collagephoto_4","type":"photo","required":false},{"label":"collagephoto_5","type":"photo","required":false}]'::jsonb, null, true, null),
  ('common-collage-6', 'Коллаж из 6 фото', 'common-section', 'common', '{"photos_collage":6}'::jsonb, '[{"label":"collagephoto_1","type":"photo","required":false},{"label":"collagephoto_2","type":"photo","required":false},{"label":"collagephoto_3","type":"photo","required":false},{"label":"collagephoto_4","type":"photo","required":false},{"label":"collagephoto_5","type":"photo","required":false},{"label":"collagephoto_6","type":"photo","required":false}]'::jsonb, null, true, null),
  ('common-full-page', 'Общее фото (страница)', 'common-section', 'common', '{"photos_full":1}'::jsonb, '[{"label":"classphotoframe","type":"photo","required":true}]'::jsonb, null, true, null),
  ('common-spread', 'Общее фото (разворот)', 'common-section', 'common', '{"photos_full":1}'::jsonb, '[{"label":"spreadphoto","type":"photo","required":true}]'::jsonb, 'spread', true, null),
  ('common-half', 'Два фото (½)', 'common-section', 'common', '{"photos_half":2}'::jsonb, '[{"label":"halfphoto_1","type":"photo","required":false},{"label":"halfphoto_2","type":"photo","required":false}]'::jsonb, null, true, null),
  ('common-quarter', 'Два фото (¼)', 'common-section', 'common', '{"photos_quarter":2}'::jsonb, '[{"label":"quarterphoto_1","type":"photo","required":false},{"label":"quarterphoto_2","type":"photo","required":false}]'::jsonb, null, true, null),
  ('common-sixth', 'Шесть мелких фото', 'common-section', 'common', '{"photos_sixth":6}'::jsonb, '[{"label":"sixthphoto_1","type":"photo","required":false},{"label":"sixthphoto_2","type":"photo","required":false},{"label":"sixthphoto_3","type":"photo","required":false},{"label":"sixthphoto_4","type":"photo","required":false},{"label":"sixthphoto_5","type":"photo","required":false},{"label":"sixthphoto_6","type":"photo","required":false}]'::jsonb, null, true, null),
  ('grid-mini-12', 'Сетка на 12 (мини)', 'student-section', 'student_grid', '{"has_name":true,"students":12,"has_quote":false,"photos_full":0,"has_portrait":true}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentportrait_2","type":"photo","required":true},{"label":"studentportrait_3","type":"photo","required":true},{"label":"studentportrait_4","type":"photo","required":true},{"label":"studentportrait_5","type":"photo","required":true},{"label":"studentportrait_6","type":"photo","required":true},{"label":"studentportrait_7","type":"photo","required":true},{"label":"studentportrait_8","type":"photo","required":true},{"label":"studentportrait_9","type":"photo","required":true},{"label":"studentportrait_10","type":"photo","required":true},{"label":"studentportrait_11","type":"photo","required":true},{"label":"studentportrait_12","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentname_2","type":"text","required":true},{"label":"studentname_3","type":"text","required":true},{"label":"studentname_4","type":"text","required":true},{"label":"studentname_5","type":"text","required":true},{"label":"studentname_6","type":"text","required":true},{"label":"studentname_7","type":"text","required":true},{"label":"studentname_8","type":"text","required":true},{"label":"studentname_9","type":"text","required":true},{"label":"studentname_10","type":"text","required":true},{"label":"studentname_11","type":"text","required":true},{"label":"studentname_12","type":"text","required":true}]'::jsonb, null, true, null),
  ('grid-mini-4-combined', 'Сетка на 4 + общее фото (мини)', 'student-section', 'student_grid', '{"has_name":true,"students":4,"has_quote":false,"photos_full":1,"has_portrait":true}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentportrait_2","type":"photo","required":true},{"label":"studentportrait_3","type":"photo","required":true},{"label":"studentportrait_4","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentname_2","type":"text","required":true},{"label":"studentname_3","type":"text","required":true},{"label":"studentname_4","type":"text","required":true},{"label":"classphotoframe","type":"photo","required":false}]'::jsonb, null, true, null),
  ('grid-light-6', 'Сетка на 6 (лайт)', 'student-section', 'student_grid', '{"has_name":true,"students":6,"has_quote":false,"photos_full":0,"has_portrait":true}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentportrait_2","type":"photo","required":true},{"label":"studentportrait_3","type":"photo","required":true},{"label":"studentportrait_4","type":"photo","required":true},{"label":"studentportrait_5","type":"photo","required":true},{"label":"studentportrait_6","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentname_2","type":"text","required":true},{"label":"studentname_3","type":"text","required":true},{"label":"studentname_4","type":"text","required":true},{"label":"studentname_5","type":"text","required":true},{"label":"studentname_6","type":"text","required":true}]'::jsonb, null, true, null),
  ('grid-light-3-combined', 'Сетка на 3 + общее фото (лайт)', 'student-section', 'student_grid', '{"has_name":true,"students":3,"has_quote":false,"photos_full":1,"has_portrait":true}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentportrait_2","type":"photo","required":true},{"label":"studentportrait_3","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentname_2","type":"text","required":true},{"label":"studentname_3","type":"text","required":true},{"label":"classphotoframe","type":"photo","required":false}]'::jsonb, null, true, null),
  ('grid-medium-4', 'Сетка на 4 с цитатами (медиум)', 'student-section', 'student_grid', '{"has_name":true,"students":4,"has_quote":true,"photos_full":0,"has_portrait":true}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentportrait_2","type":"photo","required":true},{"label":"studentportrait_3","type":"photo","required":true},{"label":"studentportrait_4","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentname_2","type":"text","required":true},{"label":"studentname_3","type":"text","required":true},{"label":"studentname_4","type":"text","required":true},{"label":"studentquote_1","type":"text","required":false},{"label":"studentquote_2","type":"text","required":false},{"label":"studentquote_3","type":"text","required":false},{"label":"studentquote_4","type":"text","required":false}]'::jsonb, null, true, null),
  ('grid-medium-2-combined', 'Сетка на 2 с цитатами + общее (медиум)', 'student-section', 'student_grid', '{"has_name":true,"students":2,"has_quote":true,"photos_full":1,"has_portrait":true}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentportrait_2","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentname_2","type":"text","required":true},{"label":"studentquote_1","type":"text","required":false},{"label":"studentquote_2","type":"text","required":false},{"label":"classphotoframe","type":"photo","required":false}]'::jsonb, null, true, null),
  ('grid-tail-2', 'Хвостовая сетка на 2 + общее', 'common-section', 'student_grid', '{"students":2,"photos_full":1}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentportrait_2","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentname_2","type":"text","required":true},{"label":"classphotoframe","type":"photo","required":false}]'::jsonb, 'left', true, 'family в данных = common-section, по роли student_grid — выправить при перезаливке дизайна'),
  ('grid-tail-3', 'Хвостовая сетка на 3 + общее', 'common-section', 'student_grid', '{"students":3,"photos_full":1}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentportrait_2","type":"photo","required":true},{"label":"studentportrait_3","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentname_2","type":"text","required":true},{"label":"studentname_3","type":"text","required":true},{"label":"classphotoframe","type":"photo","required":false}]'::jsonb, 'left', true, 'family в данных = common-section, по роли student_grid — выправить при перезаливке дизайна'),
  ('grid-tail-4', 'Хвостовая сетка на 4 + общее', 'common-section', 'student_grid', '{"students":4,"photos_full":1}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentportrait_2","type":"photo","required":true},{"label":"studentportrait_3","type":"photo","required":true},{"label":"studentportrait_4","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentname_2","type":"text","required":true},{"label":"studentname_3","type":"text","required":true},{"label":"studentname_4","type":"text","required":true},{"label":"classphotoframe","type":"photo","required":false}]'::jsonb, 'left', true, 'family в данных = common-section, по роли student_grid — выправить при перезаливке дизайна'),
  ('personal-standard-left', 'Личная (стандарт), лево', 'student-section', 'student_left', '{"has_name":true,"students":1,"has_quote":true,"has_portrait":true,"photos_friend":0}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentquote_1","type":"text","required":false}]'::jsonb, 'left', true, null),
  ('personal-universal-left', 'Личная (универсал, 2 друга), лево', 'student-section', 'student_left', '{"has_name":true,"students":1,"has_quote":true,"has_portrait":true,"photos_friend":2}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentquote_1","type":"text","required":false},{"label":"studentphoto_1","type":"photo","required":false},{"label":"studentphoto_2","type":"photo","required":false}]'::jsonb, 'left', true, null),
  ('personal-max-left', 'Личная (макси, без цитаты), лево', 'student-section', 'student_left', '{"has_name":true,"students":1,"has_quote":false,"has_portrait":true,"photos_friend":0}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true}]'::jsonb, 'left', true, null),
  ('personal-standard-right', 'Личная (стандарт), право', 'student-section', 'student_right', '{"has_name":true,"students":1,"has_quote":true,"has_portrait":true,"photos_friend":0}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentquote_1","type":"text","required":false}]'::jsonb, 'right', true, null),
  ('personal-universal-right', 'Личная (универсал, 2 друга), право', 'student-section', 'student_right', '{"has_name":true,"students":1,"has_quote":true,"has_portrait":true,"photos_friend":2}'::jsonb, '[{"label":"studentportrait_1","type":"photo","required":true},{"label":"studentname_1","type":"text","required":true},{"label":"studentquote_1","type":"text","required":false},{"label":"studentphoto_1","type":"photo","required":false},{"label":"studentphoto_2","type":"photo","required":false}]'::jsonb, 'right', true, null),
  ('personal-max-right', 'Личная (макси, 4 друга+цитата), право', 'student-section', 'student_right', '{"has_name":false,"students":1,"has_quote":true,"has_portrait":false,"photos_friend":4}'::jsonb, '[{"label":"studentphoto_1","type":"photo","required":true},{"label":"studentphoto_2","type":"photo","required":true},{"label":"studentphoto_3","type":"photo","required":true},{"label":"studentphoto_4","type":"photo","required":true},{"label":"studentquote_1","type":"text","required":false}]'::jsonb, 'right', true, null),
  ('friends-collage-2', 'Друзья: коллаж из 2', 'student-section', 'student_right', '{"has_name":false,"students":0,"has_quote":false,"has_portrait":false,"photos_friend":2}'::jsonb, '[{"label":"studentphoto_1","type":"photo","required":true},{"label":"studentphoto_2","type":"photo","required":true}]'::jsonb, null, true, null),
  ('friends-collage-3', 'Друзья: коллаж из 3', 'student-section', 'student_right', '{"has_name":false,"students":0,"has_quote":false,"has_portrait":false,"photos_friend":3}'::jsonb, '[{"label":"studentphoto_1","type":"photo","required":true},{"label":"studentphoto_2","type":"photo","required":true},{"label":"studentphoto_3","type":"photo","required":true}]'::jsonb, null, true, null),
  ('friends-collage-4', 'Друзья: коллаж из 4', 'student-section', 'student_right', '{"has_name":false,"students":0,"has_quote":false,"has_portrait":false,"photos_friend":4}'::jsonb, '[{"label":"studentphoto_1","type":"photo","required":true},{"label":"studentphoto_2","type":"photo","required":true},{"label":"studentphoto_3","type":"photo","required":true},{"label":"studentphoto_4","type":"photo","required":true}]'::jsonb, null, true, null),
  ('friends-collage-5', 'Друзья: коллаж из 5', 'student-section', 'student_right', '{"has_name":false,"students":0,"has_quote":false,"has_portrait":false,"photos_friend":5}'::jsonb, '[{"label":"studentphoto_1","type":"photo","required":true},{"label":"studentphoto_2","type":"photo","required":true},{"label":"studentphoto_3","type":"photo","required":true},{"label":"studentphoto_4","type":"photo","required":true},{"label":"studentphoto_5","type":"photo","required":true}]'::jsonb, null, true, null),
  ('friends-collage-6', 'Друзья: коллаж из 6', 'student-section', 'student_right', '{"has_name":false,"students":0,"has_quote":false,"has_portrait":false,"photos_friend":6}'::jsonb, '[{"label":"studentphoto_1","type":"photo","required":true},{"label":"studentphoto_2","type":"photo","required":true},{"label":"studentphoto_3","type":"photo","required":true},{"label":"studentphoto_4","type":"photo","required":true},{"label":"studentphoto_5","type":"photo","required":true},{"label":"studentphoto_6","type":"photo","required":true}]'::jsonb, null, true, null),
  ('head-only', 'Классрук (только портрет)', 'head-teacher', 'teacher_left', '{"teachers":0,"head_teacher":1}'::jsonb, '[{"label":"headteacherphoto_1","type":"photo","required":true},{"label":"headteachername_1","type":"text","required":true},{"label":"headteacherrole_1","type":"text","required":false},{"label":"headtextframe","type":"text","required":false}]'::jsonb, null, true, null),
  ('head-with-classphoto', 'Классрук + общее фото', 'head-teacher', 'teacher_left', '{"photos_full":1,"head_teacher":1}'::jsonb, '[{"label":"headteacherphoto_1","type":"photo","required":true},{"label":"headteachername_1","type":"text","required":true},{"label":"headteacherrole_1","type":"text","required":false},{"label":"headtextframe","type":"text","required":false},{"label":"classphotoframe","type":"photo","required":false}]'::jsonb, 'left', true, null),
  ('head-with-4-teachers', 'Классрук + 4 учителя', 'head-teacher', 'teacher_left', '{"teachers":4,"head_teacher":1}'::jsonb, '[{"label":"headteacherphoto_1","type":"photo","required":true},{"label":"headteachername_1","type":"text","required":true},{"label":"headteacherrole_1","type":"text","required":false},{"label":"headtextframe","type":"text","required":false},{"label":"teacherphoto_1","type":"photo","required":true},{"label":"teacherphoto_2","type":"photo","required":true},{"label":"teacherphoto_3","type":"photo","required":true},{"label":"teacherphoto_4","type":"photo","required":true},{"label":"teachername_1","type":"text","required":false},{"label":"teachername_2","type":"text","required":false},{"label":"teachername_3","type":"text","required":false},{"label":"teachername_4","type":"text","required":false},{"label":"teacherrole_1","type":"text","required":false},{"label":"teacherrole_2","type":"text","required":false},{"label":"teacherrole_3","type":"text","required":false},{"label":"teacherrole_4","type":"text","required":false}]'::jsonb, null, true, null),
  ('head-with-8-teachers', 'Классрук + 8 учителей', 'head-teacher', 'teacher_left', '{"teachers":8,"head_teacher":1}'::jsonb, '[{"label":"headteacherphoto_1","type":"photo","required":true},{"label":"headteachername_1","type":"text","required":true},{"label":"headteacherrole_1","type":"text","required":false},{"label":"headtextframe","type":"text","required":false},{"label":"teacherphoto_1","type":"photo","required":true},{"label":"teacherphoto_2","type":"photo","required":true},{"label":"teacherphoto_3","type":"photo","required":true},{"label":"teacherphoto_4","type":"photo","required":true},{"label":"teacherphoto_5","type":"photo","required":true},{"label":"teacherphoto_6","type":"photo","required":true},{"label":"teacherphoto_7","type":"photo","required":true},{"label":"teacherphoto_8","type":"photo","required":true},{"label":"teachername_1","type":"text","required":false},{"label":"teachername_2","type":"text","required":false},{"label":"teachername_3","type":"text","required":false},{"label":"teachername_4","type":"text","required":false},{"label":"teachername_5","type":"text","required":false},{"label":"teachername_6","type":"text","required":false},{"label":"teachername_7","type":"text","required":false},{"label":"teachername_8","type":"text","required":false},{"label":"teacherrole_1","type":"text","required":false},{"label":"teacherrole_2","type":"text","required":false},{"label":"teacherrole_3","type":"text","required":false},{"label":"teacherrole_4","type":"text","required":false},{"label":"teacherrole_5","type":"text","required":false},{"label":"teacherrole_6","type":"text","required":false},{"label":"teacherrole_7","type":"text","required":false},{"label":"teacherrole_8","type":"text","required":false}]'::jsonb, null, true, null),
  ('teachers-6', 'Учителя: 6', 'subject-teachers', 'teacher_right', '{"teachers":6}'::jsonb, '[{"label":"teacherphoto_1","type":"photo","required":true},{"label":"teacherphoto_2","type":"photo","required":true},{"label":"teacherphoto_3","type":"photo","required":true},{"label":"teacherphoto_4","type":"photo","required":true},{"label":"teacherphoto_5","type":"photo","required":true},{"label":"teacherphoto_6","type":"photo","required":true},{"label":"teachername_1","type":"text","required":false},{"label":"teachername_2","type":"text","required":false},{"label":"teachername_3","type":"text","required":false},{"label":"teachername_4","type":"text","required":false},{"label":"teachername_5","type":"text","required":false},{"label":"teachername_6","type":"text","required":false},{"label":"teacherrole_1","type":"text","required":false},{"label":"teacherrole_2","type":"text","required":false},{"label":"teacherrole_3","type":"text","required":false},{"label":"teacherrole_4","type":"text","required":false},{"label":"teacherrole_5","type":"text","required":false},{"label":"teacherrole_6","type":"text","required":false}]'::jsonb, 'right', true, null),
  ('teachers-9', 'Учителя: 9', 'subject-teachers', 'teacher_right', '{"teachers":9}'::jsonb, '[{"label":"teacherphoto_1","type":"photo","required":true},{"label":"teacherphoto_2","type":"photo","required":true},{"label":"teacherphoto_3","type":"photo","required":true},{"label":"teacherphoto_4","type":"photo","required":true},{"label":"teacherphoto_5","type":"photo","required":true},{"label":"teacherphoto_6","type":"photo","required":true},{"label":"teacherphoto_7","type":"photo","required":true},{"label":"teacherphoto_8","type":"photo","required":true},{"label":"teacherphoto_9","type":"photo","required":true},{"label":"teachername_1","type":"text","required":false},{"label":"teachername_2","type":"text","required":false},{"label":"teachername_3","type":"text","required":false},{"label":"teachername_4","type":"text","required":false},{"label":"teachername_5","type":"text","required":false},{"label":"teachername_6","type":"text","required":false},{"label":"teachername_7","type":"text","required":false},{"label":"teachername_8","type":"text","required":false},{"label":"teachername_9","type":"text","required":false},{"label":"teacherrole_1","type":"text","required":false},{"label":"teacherrole_2","type":"text","required":false},{"label":"teacherrole_3","type":"text","required":false},{"label":"teacherrole_4","type":"text","required":false},{"label":"teacherrole_5","type":"text","required":false},{"label":"teacherrole_6","type":"text","required":false},{"label":"teacherrole_7","type":"text","required":false},{"label":"teacherrole_8","type":"text","required":false},{"label":"teacherrole_9","type":"text","required":false}]'::jsonb, 'right', true, null),
  ('teachers-12', 'Учителя: 12', 'subject-teachers', 'teacher_right', '{"teachers":12}'::jsonb, '[{"label":"teacherphoto_1","type":"photo","required":true},{"label":"teacherphoto_2","type":"photo","required":true},{"label":"teacherphoto_3","type":"photo","required":true},{"label":"teacherphoto_4","type":"photo","required":true},{"label":"teacherphoto_5","type":"photo","required":true},{"label":"teacherphoto_6","type":"photo","required":true},{"label":"teacherphoto_7","type":"photo","required":true},{"label":"teacherphoto_8","type":"photo","required":true},{"label":"teacherphoto_9","type":"photo","required":true},{"label":"teacherphoto_10","type":"photo","required":true},{"label":"teacherphoto_11","type":"photo","required":true},{"label":"teacherphoto_12","type":"photo","required":true},{"label":"teachername_1","type":"text","required":false},{"label":"teachername_2","type":"text","required":false},{"label":"teachername_3","type":"text","required":false},{"label":"teachername_4","type":"text","required":false},{"label":"teachername_5","type":"text","required":false},{"label":"teachername_6","type":"text","required":false},{"label":"teachername_7","type":"text","required":false},{"label":"teachername_8","type":"text","required":false},{"label":"teachername_9","type":"text","required":false},{"label":"teachername_10","type":"text","required":false},{"label":"teachername_11","type":"text","required":false},{"label":"teachername_12","type":"text","required":false},{"label":"teacherrole_1","type":"text","required":false},{"label":"teacherrole_2","type":"text","required":false},{"label":"teacherrole_3","type":"text","required":false},{"label":"teacherrole_4","type":"text","required":false},{"label":"teacherrole_5","type":"text","required":false},{"label":"teacherrole_6","type":"text","required":false},{"label":"teacherrole_7","type":"text","required":false},{"label":"teacherrole_8","type":"text","required":false},{"label":"teacherrole_9","type":"text","required":false},{"label":"teacherrole_10","type":"text","required":false},{"label":"teacherrole_11","type":"text","required":false},{"label":"teacherrole_12","type":"text","required":false}]'::jsonb, 'right', true, null),
  ('teachers-16', 'Учителя: 16', 'subject-teachers', 'teacher_right', '{"teachers":16}'::jsonb, '[{"label":"teacherphoto_1","type":"photo","required":true},{"label":"teacherphoto_2","type":"photo","required":true},{"label":"teacherphoto_3","type":"photo","required":true},{"label":"teacherphoto_4","type":"photo","required":true},{"label":"teacherphoto_5","type":"photo","required":true},{"label":"teacherphoto_6","type":"photo","required":true},{"label":"teacherphoto_7","type":"photo","required":true},{"label":"teacherphoto_8","type":"photo","required":true},{"label":"teacherphoto_9","type":"photo","required":true},{"label":"teacherphoto_10","type":"photo","required":true},{"label":"teacherphoto_11","type":"photo","required":true},{"label":"teacherphoto_12","type":"photo","required":true},{"label":"teacherphoto_13","type":"photo","required":true},{"label":"teacherphoto_14","type":"photo","required":true},{"label":"teacherphoto_15","type":"photo","required":true},{"label":"teacherphoto_16","type":"photo","required":true},{"label":"teachername_1","type":"text","required":false},{"label":"teachername_2","type":"text","required":false},{"label":"teachername_3","type":"text","required":false},{"label":"teachername_4","type":"text","required":false},{"label":"teachername_5","type":"text","required":false},{"label":"teachername_6","type":"text","required":false},{"label":"teachername_7","type":"text","required":false},{"label":"teachername_8","type":"text","required":false},{"label":"teachername_9","type":"text","required":false},{"label":"teachername_10","type":"text","required":false},{"label":"teachername_11","type":"text","required":false},{"label":"teachername_12","type":"text","required":false},{"label":"teachername_13","type":"text","required":false},{"label":"teachername_14","type":"text","required":false},{"label":"teachername_15","type":"text","required":false},{"label":"teachername_16","type":"text","required":false},{"label":"teacherrole_1","type":"text","required":false},{"label":"teacherrole_2","type":"text","required":false},{"label":"teacherrole_3","type":"text","required":false},{"label":"teacherrole_4","type":"text","required":false},{"label":"teacherrole_5","type":"text","required":false},{"label":"teacherrole_6","type":"text","required":false},{"label":"teacherrole_7","type":"text","required":false},{"label":"teacherrole_8","type":"text","required":false},{"label":"teacherrole_9","type":"text","required":false},{"label":"teacherrole_10","type":"text","required":false},{"label":"teacherrole_11","type":"text","required":false},{"label":"teacherrole_12","type":"text","required":false},{"label":"teacherrole_13","type":"text","required":false},{"label":"teacherrole_14","type":"text","required":false},{"label":"teacherrole_15","type":"text","required":false},{"label":"teacherrole_16","type":"text","required":false}]'::jsonb, 'right', true, null),
  ('class-full', 'Групповое фото класса', 'class-photo', 'teacher_right', '{"photos_full":1}'::jsonb, '[{"label":"classphotoframe","type":"photo","required":true}]'::jsonb, null, true, null),
  ('class-half', 'Групповые фото (½)', 'class-photo', 'teacher_right', '{"photos_half":2}'::jsonb, '[{"label":"halfphoto_1","type":"photo","required":true},{"label":"halfphoto_2","type":"photo","required":true}]'::jsonb, null, true, null),
  ('title-page', 'Заглавный лист', 'intro', 'intro', '{"photos_full":1}'::jsonb, '[{"label":"classphotoframe","type":"photo","required":false}]'::jsonb, 'right', true, null),
  ('final-page', 'Финальный лист', 'final', 'final', '{"photos_full":1}'::jsonb, '[{"label":"classphotoframe","type":"photo","required":false}]'::jsonb, 'left', true, null)
on conflict (code) do update set
  display_name    = excluded.display_name,
  family_id       = excluded.family_id,
  page_role       = excluded.page_role,
  slot_capacity   = excluded.slot_capacity,
  canonical_slots = excluded.canonical_slots,
  page_type       = excluded.page_type,
  is_active       = excluded.is_active,
  notes           = excluded.notes;

-- Backfill: проставить мастерам akvarel/belly ссылку на тип по (page_role + slot_capacity).
-- Неоднозначность common photos_full:1 (страница J-Full vs разворот J-Spread) разводим
-- по page_type: 'spread' → common-spread, иначе → common-full-page.
update spread_templates st
set master_page_type_id = mpt.id
from master_page_types mpt
where st.template_set_id in (select id from template_sets where slug in ('akvarel','belly'))
  and st.page_role is not null and st.slot_capacity is not null
  and st.page_role = mpt.page_role
  and st.slot_capacity = mpt.slot_capacity
  and (
    mpt.code not in ('common-spread','common-full-page')
    or (mpt.code = 'common-spread'    and st.page_type = 'spread')
    or (mpt.code = 'common-full-page' and st.page_type is distinct from 'spread')
  );
